services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - huggingface_cache:/root/.cache/huggingface
      - ./media:/app/media
    environment:
      - TRANSFORMERS_CACHE=/root/.cache/huggingface
      - HF_HOME=/root/.cache/huggingface
      - MODE=${MODE:-daily}
      - WEBSHARE_API_KEY=${WEBSHARE_API_KEY}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GOOGLE_SEARCH_ENGINE_ID=${GOOGLE_SEARCH_ENGINE_ID}
      - UNSPLASH_ACCESS_KEY=${UNSPLASH_ACCESS_KEY}
      - LOCAL_DB_URL=${LOCAL_DB_URL}
      - SUPABASE_ACCESS_ID=${SUPABASE_ACCESS_ID}
      - SUPABASE_SECRET_KEY=${SUPABASE_SECRET_KEY}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - DB_TYPE=${DB_TYPE}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - IMAGEN_API_KEY=${IMAGEN_API_KEY}
    entrypoint: ["/bin/sh", "-c"]
    command: |
      "/start.sh && exit"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_NAME:-newsdb}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  postgres_data:
  huggingface_cache:
